// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://souundspljqbxamhkpof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdXVuZHNwbGpxYnhhbWhrcG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDE1MTUsImV4cCI6MjA3MDYxNzUxNX0.LPeNYerleHsnBtinEXejsuXPMZReeWlA4o2LSY0yfM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});